language: java
sudo: false
script: mvn verify

jdk:
  - openjdk8
  - openjdk11

## env:
##   global:
##     - JAVA_OPTS="-Xmx1024M -Xms512M"

notifications:
  email:
    # [always|never|change]
    on_success: change
    on_failure: always
